#!/usr/bin/env python
# Copyright (C) 2015 Peter Helbing <peter@abulafia.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import sqlite3
import time

sys.path.insert(0, '/usr/share/anki')
from anki import storage, stats

deckname = os.environ.get('BLOCK_INSTANCE')
if deckname is None or deckname == '':
    deckname = 'core6k'

succ = False
for i in range(1,10):
    try:
        col = storage.Collection('/home/peter/Anki/Benutzer 1/collection.anki2')
    except sqlite3.OperationalError:
        time.sleep(0.1)
        continue
    succ = True
    break

if not succ:
    print '-'
    sys.exit(1)
    
st = stats.CollectionStats(col)

prev = col.decks.selected()

x = col.decks.byName(deckname)
if x is not None:
    col.decks.select(int(x['id']))
else:
    print '-'
    col.decks.select(prev)
    sys.exit(1)

st = stats.CollectionStats(col)
due = st._due(-1000, 1, 1)

if len(due):
    print sum([ x[1] + x[2] for x in due ])
else:
    print 0

col.decks.select(prev)
