#!/usr/bin/env python
# Copyright (C) 2015 Peter Helbing <peter@abulafia.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import imaplib, netrc, os

n = netrc.netrc()

outstring = ''

server = os.environ.get('BLOCK_INSTANCE')

if server not in n.hosts.keys():
    outstring = 'err'
else:
    usern = n.hosts[server][0]
    passw = n.hosts[server][2]
    try:
        m = imaplib.IMAP4_SSL(server,993)
        m.login(usern, passw)
        status, counts = m.status("INBOX","(MESSAGES UNSEEN)")
        outstring = counts[0].split()[4][:-1]
    except Exception, e:
        outstring = 'err'

print outstring
